### ISSUE TITLE
When using go/install with cache:true, existing installation is not properly cleaned

### ISSUE THREAD

**Issue by ZFLloyd** [CircleCI-Public/go-orb#46]
Hello @felicianotech ! I've been trying to set-up CI for a project and I encountered the following issue

We are using a machine executor and then trying to install go through the command provided by the orb: 
```yaml
machine:
  image: ubuntu-2004:202101-01
steps:
    - checkout
    - go/install:
        cache: true
        version: 1.16.3
```

Without using the cache, the install script properly cleans the existing go installation (`1.15.6` if I remember well) before installing the new version.
But if we set `cache:true` it seems it is not getting cleaned properly as we get this kind of errors when using `go` after:

```
/usr/local/go/src/runtime/mgcsweepbuf.go:87:80: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/mgcsweepbuf.go:106:102: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
```

Which refers to a file removed in go 1.16, and is symptomatic of a badly cleaned installation.

Would it be possible to properly clean the existing installation when using the cached go binary ? It might be on purpose to avoid some other issues I am not aware of.

**Comment by ZFLloyd** [comment]
To be more precise in the install [script](https://github.com/CircleCI-Public/go-orb/blob/master/src/commands/install.yml)

```bash
if command -v go >/dev/null; then
  if go version | grep -q -F "go1.16.3 "; then # Binary exists after cache was restored so this is true
    echo "Binary already exists, skipping download." 
    exit 0
  fi

  echo "Found a different version of Go."
  OSD_FAMILY="$(go env GOHOSTOS)"
  HOSTTYPE="$(go env GOHOSTARCH)"

  $SUDO rm -rf /usr/local/go 
  $SUDO install --owner=${USER} -d /usr/local/go
fi
```

**Comment by ZFLloyd** [comment]
> Note: This may not actually work. I got me past the problem on the first run after introducing the `cache-key`, but further runs fail due to the same issue as described in the opening comment. However, I did verify that the cache was being pulled from the same build when the `cache-key` was added. This might be something weird with my setup though.

I never have problems on the first run either since the issue only appears when there's a cache hit, and the script actually exists without cleaning up an existing installation.

This is the cache restore command:
```yaml
- run:
            name: "Prep cache restore"
            command: |
              $SUDO mkdir -p /usr/local/go
              $SUDO chown -R $(whoami): /usr/local/go
```

If we just change it to include a clean-up of an existing install it should behave properly I believe. I'll try to make the Pull Request and see how it goes.
