### ISSUE TITLE
Make cache file path a configurable variable [continued]

### ISSUE THREAD

**Issue by gonzaloserrano** [CircleCI-Public/go-orb#51]
https://github.com/CircleCI-Public/go-orb/issues/33 made cache save configurable, but not cache load.

Also, what do you think about using `$GOPATH` instead of hardcoding the directory?

E.g something like
```yaml
    default: "${GOPATH}/pkg/mod"
```

I'm trying to do this without success:

```yaml
      - go/load-cache:
          path: /root/go/pkg/mod
      - run: make mod
      - go/save-cache:
          path: /root/go/pkg/mod
```

where `make mod` does a `go mod download` with some PROXY stuff and then a `go mod tidy`
