### ISSUE TITLE
incorrect hosttype on arm ubuntu machine images

### ISSUE THREAD

**Issue by amwill04** [CircleCI-Public/go-orb#64]
given the following:

```yaml
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: arm.medium
    steps:
      - checkout
      - go/install:
          version: 1.19.3
```

It fails as `curl` returns `404`.

Issue seems to be due to `$HOSTTYPE` being set as `aarch64` which does go binary not existing at `https://dl.google.com/go/go1.19.3.linux-aarch64.tar.gz`
