### ISSUE TITLE
Set issue with executor 1.19

### ISSUE THREAD

**Issue by adamdavis40208** [CircleCI-Public/go-orb#69]
Circle file:
```
version: 2.1

orbs:
  go: circleci/go@1

jobs:
  test:
    executor:
      name: go/default
      tag: '1.19'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  version: 2
  janus-pipeline:
    jobs:
      - test:
          context: cambia
```

Circle job failing with:
```
/bin/bash: line 9: set: -c: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
```
