### ISSUE TITLE
`go/test` with no parameters fails on versions > 1.7.1

### ISSUE THREAD

**Issue by milesarmstrong** [CircleCI-Public/go-orb#79]
Hiya! My job looks like:

```
  test_golang:
    executor:
      name: go/default
      tag: "1.21"
    steps:
      - checkout:
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test
```

and I get this error

```
+ go test -count=1 -coverprofile=cover-source.out -p 1 -covermode=set ./... -coverpkg=./... -race -failfast -short -v
-covermode must be "atomic", not "set", when -race is enabled

Exited with code exit status 1
```

on any version > `1.7.1`
